language: android
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-25.0.2
    - android-25

    # Support library
    - extra-android-support
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-22
script:
- chmod +x ./gradlew
- echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
- echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
- android-wait-for-emulator             #Run wait for the emulator script.
- adb devices                           #Display list of devices
- adb shell input keyevent 82 &
- ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.26'
    - 'google-gdk-license-.+'
