version: 2

dependencies:
  cache_directories:
    - ~/.gradle
    - ~/.android

  override:
    - echo y | android update sdk --no-ui --all --filter "platform-tools, tools"
    - echo y | android update sdk --no-ui --all --filter "android-22, build-tools-22.0.1"
    - echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
    - echo y | android update sdk --no-ui --all --filter "extra-android-support"

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  test:
    pre:
    # start the emulator
      - emulator -avd circleci-android22 -no-audio -no-window:
          background: true
          parallel: true
      # wait for it to have booted
      - circle-android wait-for-boot
      # unlock the emulator screen
      - sleep 30
      - adb shell input keyevent 82

    override:
      # run tests against the emulator.
            - ./gradlew connectedAndroidTest -PdisablePreDex

  test:
    post:
          - bash <(curl -s https://codecov.io/bash)